# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
# Import your libraries:
import numpy as np
import pandas as pd

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function ([documentation](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html)).

In [2]:
# Loading the dataset:

from sklearn.datasets import load_diabetes
diabetes = load_diabetes()

Let's explore this variable by looking at the different attributes (keys) of `diabetes`. Note that the `load_diabetes` function does not return dataframes. It returns you a Python dictionary.

In [3]:
print("diabetes.keys(): \n{}".format(diabetes.keys()))

diabetes.keys(): 
dict_keys(['data', 'target', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])


#### The next step is to read the description of the dataset. 

Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable. Read the data description carefully to fully understand what each column represents.

*Hint: If your output is ill-formatted by displaying linebreaks as `\n`, it means you are not using the `print` function.*

In [4]:
# Your code here:
print(diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - Age
      - Sex
      - Body mass index
      - Average blood pressure
      - S1
      - S2
      - S3
      - S4
      - S5
      - S6

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bra

#### Based on the data description, answer the following questions:

1. How many attributes are there in the data? What do they mean?

1. What is the relation between `diabetes['data']` and `diabetes['target']`?

1. How many records are there in the data?

In [5]:
# Enter your answer here:
# There are 10 attributes in the data
# The target is the variable we want to predict, the data are the features we will use to predict the target
# There are 442 records in the data

#### Now explore what are contained in the *data* portion as well as the *target* portion of `diabetes`. 

Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). Inspect the shape of `data` and `target`. Confirm they are consistent with the data description.

In [6]:
data = pd.DataFrame(diabetes['data'], columns = diabetes['feature_names'])
target = pd.DataFrame(diabetes['target'], columns = ['target'])
data

# The dataframe is consistent with the data description

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019908 -0.017646  
1   -0.039493 -0.068330 -0.092204  
2   -0.002592  0.002864 -0.025930  
3    0.034309  0.022692 -0.009362  
4   -0.002592 -0.031991 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018118  0.044485  
439 -0.011080 -0.046879  0.015491  
440  0.026560  0.044528 -0.025930  
441 -0.039493 -0.004220  0.003064  

[442 rows x 10 columns]

In [7]:
# Checking the target columnn
target

target
0     151.0
1      75.0
2     141.0
3     206.0
4     135.0
..      ...
437   178.0
438   104.0
439   132.0
440   220.0
441    57.0

[442 rows x 1 columns]

# Challenge 2 - Perform Supervised Learning on the Dataset

The data have already been split to predictor (*data*) and response (*target*) variables. Given this information, we'll apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset.

#### Let's briefly revisit the linear regression formula:

```
y = β0 + β1X1 + β2X2 + ... + βnXn + ϵ
```

...where:

- X1-Xn: data 
- β0: intercept 
- β1-βn: coefficients 
- ϵ: error (cannot explained by model)
- y: target

Also take a look at the `sklearn.linear_model.LinearRegression` [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html).

#### In the cell below, import the `linear_model` class from `sklearn`. 

In [8]:
# Your code here:
from sklearn.linear_model import LinearRegression

#### Create a new instance of the linear regression model and assign the new instance to the variable `diabetes_model`.

In [9]:
# Your code here:
diabetes_model = LinearRegression()

#### Next, let's split the training and test data.

Define `diabetes_data_train`, `diabetes_target_train`, `diabetes_data_test`, and `diabetes_target_test`. Use the last 20 records for the test data and the rest for the training data.

In [44]:
# Your code here:
from sklearn.model_selection import train_test_split

diabetes_data_train, diabetes_data_test, diabetes_target_train, diabetes_target_test = train_test_split(data, target,random_state = 0, test_size = 0.30)

Fit the training data and target to `diabetes_model`. Print the *intercept* and *coefficients* of the model.

In [45]:
# Your code here:
diabetes_model = diabetes_model.fit(diabetes_data_train, diabetes_target_train)

print(diabetes_model.coef_)
print(diabetes_model.intercept_)

[[ -52.46990775 -193.51064552  579.4827762   272.46404234 -504.72401371
   241.68441866  -69.73618783   86.62018451  721.95580222   26.77887028]]
[153.71914541]


#### Inspecting the results

From the outputs you should have seen:

- The intercept is a float number.
- The coefficients are an array containing 10 float numbers.

This is the linear regression model fitted to your training dataset.

#### Using your fitted linear regression model, predict the *y* of `diabetes_data_test`.

In [46]:
# Your code here:
diabetes_model.predict(diabetes_data_test)

array([[239.6785766 ],
       [250.53141737],
       [164.84805461],
       [120.27678545],
       [181.73395543],
       [262.21230671],
       [112.23276599],
       [191.94646405],
       [151.50037962],
       [236.97547898],
       [172.17106886],
       [181.76776675],
       [112.11718447],
       [ 93.10535397],
       [242.61551546],
       [ 91.18854011],
       [153.66210217],
       [ 64.67732159],
       [ 99.36843868],
       [212.25939578],
       [197.03895856],
       [162.46443162],
       [164.14281795],
       [157.73824133],
       [207.25537379],
       [170.20342369],
       [111.97456707],
       [ 82.77243482],
       [186.91705702],
       [164.72179002],
       [175.37310208],
       [ 82.34780886],
       [144.28954965],
       [149.22361436],
       [144.09115907],
       [194.25825855],
       [166.52462404],
       [188.10488874],
       [126.97750787],
       [205.91826796],
       [ 85.53348753],
       [167.78356048],
       [147.74549209],
       [183

#### Print your `diabetes_target_test` and compare with the prediction. 

In [47]:
# Your code here:
print(diabetes_target_test)

     target
362   321.0
249   215.0
271   127.0
435    64.0
400   175.0
..      ...
328    78.0
414   131.0
421   212.0
361   182.0
415   174.0

[133 rows x 1 columns]


In [48]:
from sklearn.metrics import r2_score

#R2 of the linear regression model
r2_score(diabetes_target_test, diabetes_model.predict(diabetes_data_test))

0.3928939845074757

#### Is `diabetes_target_test` exactly the same as the model prediction? Explain.

In [49]:
# Your explanation here:
diabetes_model.predict(diabetes_data_test)-diabetes_target_test

# diabetes_target_test is NOT exactly the same as the model prediction, the score of the model is only 0.39 which is not good.

target
362  -81.321423
249   35.531417
271   37.848055
435   56.276785
400    6.733955
..          ...
328  117.684568
414   34.039101
421  -18.225023
361  -69.962670
415   -1.650951

[133 rows x 1 columns]

# Bonus Challenge 1 - Hypothesis Testing with `statsmodels`

After generating the linear regression model from the dataset, you probably wonder: then what? What is the statistical way to know if my model is reliable or not?

Good question. We'll discuss that using Scikit-Learn in Challenge 5. But for now, let's use a fool-proof way by using the ([Linear Regression class of StatsModels](https://www.statsmodels.org/dev/regression.html)) which can also conduct linear regression analysis plus much more such as calcuating the F-score of the linear model as well as the standard errors and t-scores for each coefficient. The F-score and t-scores will tell you whether you can trust your linear model.

To understand the statistical meaning of conducting hypothesis testing (e.g. F-test, t-test) for slopes, read [this webpage](https://onlinecourses.science.psu.edu/stat501/node/297/) at your leisure time. We'll give you a brief overview next.

* The F-test of your linear model is to verify whether at least one of your coefficients is significantly different from zero. Translating that into the *null hypothesis* and *alternative hypothesis*, that is:

    ```
    H0 : β1 = β2 = ... = β10 = 0
    HA : At least one βj ≠ 0 (for j = 1, 2, ..., 10)
    ```

* The t-tests on each coefficient is to check whether the confidence interval for the variable contains zero. If the confidence interval contains zero, it means the null hypothesis for that variable is not rejected. In other words, this particular vaiable is not contributing to your linear model and you can remove it from your formula.

Read the documentations of [StatsModels Linear Regression](https://www.statsmodels.org/dev/regression.html) as well as its [`OLS` class](https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLS.html) which stands for *ordinary least squares*.

#### In the next cell, analyze `diabetes_data_train` and `diabetes_target_train` with the linear regression model of `statsmodels`. Print the fit summary.

Your output should look like:

![statsmodels regression](../statsmodels.png)

In [51]:
# Your code here:
import statsmodels.api as sm

# define our model -> perform the fit
model = sm.OLS(diabetes_target_train,diabetes_data_train).fit()

# define our predictions by applying the model
predictions = model.predict(diabetes_data_train)

# checking out results
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                 target   R-squared (uncentered):                   0.106
Model:                            OLS   Adj. R-squared (uncentered):              0.076
Method:                 Least Squares   F-statistic:                              3.554
Date:                Sun, 28 Jun 2020   Prob (F-statistic):                    0.000183
Time:                        23:34:51   Log-Likelihood:                         -2010.9
No. Observations:                 309   AIC:                                      4042.
Df Residuals:                     299   BIC:                                      4079.
Df Model:                          10                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
age          -94.5943    217.856     -0.434      0.664    -523.320     334.131
sex         -108.8227    220.067     -0.494      0.621    -541.900     324.254
bmi          529.9252    243.543      2.176      0.030      50.650    1009.200
bp           326.7419    248.223      1.316      0.189    -161.743     815.227
s1           181.5677   1485.137      0.122      0.903   -2741.078    3104.213
s2          -511.8037   1187.478     -0.431      0.667   -2848.677    1825.070
s3           -78.8246    776.199     -0.102      0.919   -1606.330    1448.681
s4           465.0394    589.797      0.788      0.431    -695.641    1625.719
s5           340.0635    601.944      0.565      0.573    -844.521    1524.648
s6           -20.6244    232.680     -0.089      0.929    -478.522     437.273
==============================================================================
Omnibus:                        5.785   Durbin-Watson:                   0.208
Prob(Omnibus):                  0.055   Jarque-Bera (JB):                3.806
Skew:                           0.097   Prob(JB):                        0.149
Kurtosis:                       2.492   Cond. No.                         22.1
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

#### Interpreting hypothesis testing results

Answer the following questions in the cell below:

1. What is the F-score of your linear model and is the null hypothesis rejected?

1. Does any of the t-tests of the coefficients produce a confidence interval containing zero? What are they?

1. How will you modify your linear reguression model according to the test results above?

In [16]:
# Your answers here:




# Challenge 3 - Peform Supervised Learning on a Pandas Dataframe

Now that we have dealt with data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [52]:
# Your code here:
auto = pd.read_csv(('../auto-mpg.csv'))

Look at the first 5 rows using the `head()` function:

In [53]:
# Your code here:
auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [54]:
# Your code here:
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horse_power     float64
weight            int64
acceleration    float64
model_year        int64
car_name         object
dtype: object

What is the newest model year and the oldest model year?

In [55]:
# Your code here:
auto.describe()

# The newest model year is 1982 and the oldest 1970

mpg   cylinders  displacement  horse_power       weight  \
count  398.000000  398.000000    398.000000   392.000000   398.000000   
mean    23.514573    5.454774    193.425879   104.469388  2970.424623   
std      7.815984    1.701004    104.269838    38.491160   846.841774   
min      9.000000    3.000000     68.000000    46.000000  1613.000000   
25%     17.500000    4.000000    104.250000    75.000000  2223.750000   
50%     23.000000    4.000000    148.500000    93.500000  2803.500000   
75%     29.000000    8.000000    262.000000   126.000000  3608.000000   
max     46.600000    8.000000    455.000000   230.000000  5140.000000   

       acceleration  model_year  
count    398.000000  398.000000  
mean      15.568090   76.010050  
std        2.757689    3.697627  
min        8.000000   70.000000  
25%       13.825000   73.000000  
50%       15.500000   76.000000  
75%       17.175000   79.000000  
max       24.800000   82.000000

Check the dataset for missing values and remove all rows containing at least one missing value.

In [57]:
# checking for missing values:
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     6
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

In [58]:
# Dropping all rows with missing values
auto = auto.dropna()

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [60]:
# There are 5 possible values of cylinders:
auto['cylinders'].value_counts()

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

*Hint: To separate data for training and test, use the `train_test_split` method we used in previous labs.*

In [61]:
# Your code here:
auto.drop('car_name', axis= 1, inplace= True)

In [63]:
# Train test split

X_train, X_test, y_train, y_test = train_test_split(auto.loc[:, auto.columns != 'mpg'], auto['mpg'],random_state = 0, test_size = 0.30)

Now we will processed and peform linear regression on this data to predict the mpg for each vehicle. 

#### In the next cell, create an instance of the linear regression model and call it `auto_model`. Fit `auto_model` with your training data.

In [64]:
# Your code here:
auto_model = LinearRegression()

auto_model = auto_model.fit(X_train, y_train)

print(auto_model.coef_)
print(auto_model.intercept_)

[-2.83029573e-01  2.05832904e-03 -5.78540877e-04 -6.33461712e-03
  4.81253073e-02  7.20358753e-01]
-12.141145894838534


In [69]:
print(auto_model.score(X_test,y_test))

#the accuracy of the training
print(auto_model.score(X_train, y_train))

0.7983345128838719
0.811683812593389


# Challenge 4 - Evaluate the Model

In addition to evaluating your model with F-test and t-test, you can also use the *Coefficient of Determination* (a.k.a. *r squared score*). This method does not simply tell *yes* or *no* about the model fit but instead indicates how much variation can be explained by the model. Based on the r squared score, you can decide whether to improve your model in order to obtain a better fit.

You can learn about the r squared score [here](https://en.wikipedia.org/wiki/Coefficient_of_determination). In the end, we want the r-squared score to be as high as possible.

#### In the next cell, compute the predicted *y* based on `X_train` and call it `y_pred`. Then calcualte the r squared score between `y_pred` and `y_train` which indicates how well the estimated regression model fits the training data.

*Hint: r squared score can be calculated using `sklearn.metrics.r2_score` ([documentation](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html)).*

In [78]:
# Your code here:
y_pred = auto_model.predict(X_train)

In [79]:
y_pred

array([29.6971268 , 16.86070006, 26.31601288, 33.01233664,  9.40423169,
       21.16028196, 17.0951992 , 13.38897618, 28.14409792, 28.33778904,
       34.12763246, 30.91794195, 21.33062967, 21.59423312, 24.59180987,
       24.5126738 , 13.58505517, 27.28340749,  8.43145657, 26.84452791,
       14.96556009, 25.46767281, 28.53625601, 29.11173818, 17.74658882,
       29.30199501, 24.01858358, 27.64630378, 11.88523593, 26.59023976,
       19.60980011, 12.80610506, 32.35272295, 21.76655661, 17.77669758,
       16.66971939, 33.99240168, 17.42087821, 19.04883527, 19.30497445,
       16.01248439, 21.684082  , 28.41637312, 19.47173908, 28.39163269,
       29.43770574, 27.02441346, 25.28846372, 17.69454256, 32.70299044,
       21.29452104, 23.68783755, 11.57022642, 10.83183564, 33.32887842,
       24.68938936, 31.09738897, 25.22603612, 22.98306931, 31.17685874,
       25.62620376, 33.55170645, 33.06971931,  9.44418475, 15.35113172,
       29.85057302, 12.39400069, 19.74810787, 28.67167089, 16.58

In [80]:
from sklearn.metrics import r2_score
r2_score(y_train, y_pred)

0.811683812593389

#### Our next step is to evaluate the model using the test data. 

We would like to ensure that our model is not overfitting the data. This means that our model was made to fit too closely to the training data by being overly complex. If a model is overfitted, it is not generalizable to data outside the training data. In that case, we need to reduce the complexity of the model by removing certain features (variables).

In the cell below, use the model to generate the predicted values for the test data and assign them to `y_test_pred`. Compute the r squared score of the predicted `y_test_pred` and the oberserved `y_test` data.

In [82]:
# Your code here:
y_test_pred = auto_model.predict(X_test)

r2_score(y_test, y_test_pred)

0.7983345128838719

#### Explaining the results

The r squared scores of the training data and the test data are pretty close (0.8146 vs 0.7818). This means our model is not overfitted. However, there is still room to improve the model fit. Move on to the next challenge.

# Challenge 5 - Improve the Model Fit

While the most common way to improve the fit of a model is by using [regularization](https://datanice.github.io/machine-learning-101-what-is-regularization-interactive.html), there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [94]:
# Train test split

X_train09, X_test09, y_train09, y_test09 = train_test_split(auto.loc[:, auto.columns != 'mpg'], auto['mpg'], test_size = 0.10)

Initialize a new linear regression model. Name this model `auto_model09`. Fit the model to the new sample (training) data.

In [95]:
auto_model09 = LinearRegression()

auto_model09 = auto_model09.fit(X_train09, y_train09)

print(auto_model09.coef_)
print(auto_model09.intercept_)

[-0.49136327  0.00834078  0.00089116 -0.00667012  0.04525621  0.74472598]
-13.004653344991308


Compute the predicted values and r squared score for our new model and new sample data.

In [96]:
# Your code here:

y_train_pred= auto_model09.predict(X_train09)
r2_score(y_train09, y_train_pred)

0.805910769594976

In [97]:
y_test_pred = auto_model09.predict(X_test09)
r2_score(y_test09, y_test_pred)

0.827491274744852

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [30]:
# There is an omprovement in the test r squared from 0.79 to 0.82

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [98]:
from sklearn.feature_selection import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [99]:
# Your code here:
auto_model = LinearRegression()
#Initializing RFE model
rfe = RFE(auto_model, n_features_to_select=3, step=1)
#Transforming data using RFE
X_rfe = rfe.fit_transform(X_train,y_train)  
#Fitting the data to model
auto_model.fit(X_rfe,y_train)
print(rfe.support_)

[ True False False False  True  True]
[1 3 4 2 1 1]


Fit the model and print the ranking

In [100]:
# Your code here:
print(rfe.ranking_)

[1 3 4 2 1 1]


In [101]:
X_train

cylinders  displacement  horse_power  weight  acceleration  model_year
397          4         119.0         82.0    2720          19.4          82
160          6         231.0        110.0    3907          21.0          75
143          4          97.0         78.0    2300          14.5          74
346          4          97.0         67.0    2065          17.8          81
67           8         429.0        208.0    4633          11.0          72
..         ...           ...          ...     ...           ...         ...
325          4          90.0         48.0    2085          21.7          80
194          6         232.0         90.0    3085          17.6          76
118          4         116.0         75.0    2158          15.5          73
48           6         250.0         88.0    3139          14.5          71
174          6         171.0         97.0    2984          14.5          75

[274 rows x 6 columns]

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [105]:
# Your code here:

reduced_data= auto[['cylinders', 'acceleration', 'model_year']]

X_train_reduced, X_test_reduced, y_train_reduced, y_test_reduced = train_test_split(reduced_data, auto['mpg'], test_size = 0.20)

Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [106]:
# Your code here: 
auto_model_reduced = LinearRegression()

auto_model_reduced = auto_model_reduced.fit(X_train_reduced, y_train_reduced)

print(auto_model_reduced.coef_)
print(auto_model_reduced.intercept_)

[-3.03481619 -0.06174911  0.78977598]
-18.9476490778325


In [107]:
y_train_pred= auto_model_reduced.predict(X_train_reduced)
r2_score(y_train_reduced, y_train_pred)

0.7056569058564588

In [108]:
y_test_pred = auto_model_reduced.predict(X_test_reduced)
r2_score(y_test_reduced, y_test_pred)

0.7446580420863951

#### Conclusion

You may obtain the impression from this lab that without knowing statistical methods in depth, it is difficult to make major progress in machine learning. That is correct. If you are motivated to become a data scientist, statistics is the subject you must be proficient in and there is no shortcut. 

Completing these labs is not likely to make you a data scientist. But you will have a good sense about what are there in machine learning and what are good for you. In your future career, you can choose one of the three tracks:

* Data scientists who need to be proficient in statistical methods.

* Data engineers who need to be good at programming.

* Data integration specialists who are business or content experts but also understand data and programming. This cross-disciplinary track brings together data, technology, and business and will be in high demands in the next decade.